project_name: "Gaussian_SLAM_tumrgbd"
dataset_name: "tum_rgbd"
checkpoint_path: null
frame_limit: -1 # use first n frames. for debugging, set to -1 to disable
seed: 0
# data
input_path: /home/nathan/datasets/tum/rgbd_dataset_freiburg1_desk/
output_path: output/TUM_RGBD/rgbd_dataset_freiburg1_desk/
scene_name: rgbd_dataset_freiburg1_desk
# mapping
uniform_seed_interval: 3
iterations: 100
new_submap_iterations: 100
iou_thresh: 0.05
alpha_thre: 0.6
pruning_thre: 0.5
# tracking
gt_camera: True
track_iterations: 200
cam_rot_lr: 0.002
cam_trans_lr: 0.01
# cam
depth_scale: 5000.0
H: 480
W: 640
fx: 517.3
fy: 516.5
cx: 318.6
cy: 255.3
crop_edge: 0
# distortion: [ 0.2624, -0.9531, -0.0054, 0.0026, 1.1633 ]